from ..robots.tt2d import TractorTrailer2d
from ..robots.acc_tt2d import AccTractorTrailer2d
from ..robots.kinematic_bicycle2d import KinematicBicycle2d
from ..robots.n_trailer2d import NTrailer2d

def get_env(
    env_name: str,
    case: str = "navigation",
    env_config=None,
    dt=0.2,
    H=50,
    motion_preference=0,
    collision_penalty=0.15,
    hitch_penalty=0.10,
    enable_gated_rollout_collision=True,
    enable_gated_rollout_hitch=True,
    enable_projection=False,
    enable_guidance=False,
    reward_threshold=25.0,
    ref_reward_threshold=5.0,
    max_w_theta=0.75,
    hitch_angle_weight=0.2,
    l1=3.23,
    l2=2.9,
    lh=1.15,
    lf1=0.9,
    lr=1.848,
    lf2=1.42,
    lr2=3.225,
    tractor_width=2.0,
    trailer_width=2.5,
    v_max=3.0,
    delta_max_deg=55.0,
    d_thr_factor=1.0,
    k_switch=2.5,
    steering_weight=0.05,
    preference_penalty_weight=0.05,
    heading_reward_weight=0.5,
    terminal_reward_threshold=10.0,
    terminal_reward_weight=1.0,
    ref_pos_weight=0.3,
    ref_theta1_weight=0.5,
    ref_theta2_weight=0.2,
    a_max=2.0,
    omega_max=1.0,
    num_trailers: int = 1,
):
    if env_name == "tt2d":
        if num_trailers == 0:
            return KinematicBicycle2d(
                case=case,
                env_config=env_config,
                dt=dt,
                H=H,
                motion_preference=motion_preference,
                collision_penalty=collision_penalty,
                hitch_penalty=hitch_penalty,  # ignored by bicycle
                enable_gated_rollout_collision=enable_gated_rollout_collision,
                enable_gated_rollout_hitch=enable_gated_rollout_hitch,
                enable_projection=enable_projection,
                enable_guidance=enable_guidance,
                reward_threshold=reward_threshold,
                ref_reward_threshold=ref_reward_threshold,
                max_w_theta=max_w_theta,
                hitch_angle_weight=hitch_angle_weight,  # ignored by bicycle
                l1=l1,
                l2=l2,
                lh=lh,
                lf1=lf1,
                lr=lr,
                lf2=lf2,
                lr2=lr2,
                tractor_width=tractor_width,
                trailer_width=trailer_width,
                v_max=v_max,
                delta_max_deg=delta_max_deg,
                d_thr_factor=d_thr_factor,
                k_switch=k_switch,
                steering_weight=steering_weight,
                preference_penalty_weight=preference_penalty_weight,
                heading_reward_weight=heading_reward_weight,
                terminal_reward_threshold=terminal_reward_threshold,
                terminal_reward_weight=terminal_reward_weight,
                ref_pos_weight=ref_pos_weight,
                ref_theta1_weight=ref_theta1_weight,
                ref_theta2_weight=ref_theta2_weight,
            )
        if num_trailers >= 2:
            return NTrailer2d(
                num_trailers=num_trailers,
                case=case,
                env_config=env_config,
                dt=dt,
                H=H,
                motion_preference=motion_preference,
                collision_penalty=collision_penalty,
                hitch_penalty=hitch_penalty,
                enable_gated_rollout_collision=enable_gated_rollout_collision,
                enable_gated_rollout_hitch=enable_gated_rollout_hitch,
                enable_projection=enable_projection,
                enable_guidance=enable_guidance,
                reward_threshold=reward_threshold,
                ref_reward_threshold=ref_reward_threshold,
                max_w_theta=max_w_theta,
                hitch_angle_weight=hitch_angle_weight,
                l1=l1,
                l2=l2,
                lh=lh,
                lf1=lf1,
                lr=lr,
                lf2=lf2,
                lr2=lr2,
                tractor_width=tractor_width,
                trailer_width=trailer_width,
                v_max=v_max,
                delta_max_deg=delta_max_deg,
                d_thr_factor=d_thr_factor,
                k_switch=k_switch,
                steering_weight=steering_weight,
                preference_penalty_weight=preference_penalty_weight,
                heading_reward_weight=heading_reward_weight,
                terminal_reward_threshold=terminal_reward_threshold,
                terminal_reward_weight=terminal_reward_weight,
                ref_pos_weight=ref_pos_weight,
                ref_theta1_weight=ref_theta1_weight,
                ref_theta2_weight=ref_theta2_weight,
            )
        # default single-trailer
        return TractorTrailer2d(
            case=case,
            env_config=env_config,
            dt=dt,
            H=H,
            motion_preference=motion_preference,
            collision_penalty=collision_penalty,
            hitch_penalty=hitch_penalty,
            enable_gated_rollout_collision=enable_gated_rollout_collision,
            enable_gated_rollout_hitch=enable_gated_rollout_hitch,
            enable_projection=enable_projection,
            enable_guidance=enable_guidance,
            reward_threshold=reward_threshold,
            ref_reward_threshold=ref_reward_threshold,
            max_w_theta=max_w_theta,
            hitch_angle_weight=hitch_angle_weight,
            l1=l1,
            l2=l2,
            lh=lh,
            lf1=lf1,
            lr=lr,
            lf2=lf2,
            lr2=lr2,
            tractor_width=tractor_width,
            trailer_width=trailer_width,
            v_max=v_max,
            delta_max_deg=delta_max_deg,
            d_thr_factor=d_thr_factor,
            k_switch=k_switch,
            steering_weight=steering_weight,
            preference_penalty_weight=preference_penalty_weight,
            heading_reward_weight=heading_reward_weight,
            terminal_reward_threshold=terminal_reward_threshold,
            terminal_reward_weight=terminal_reward_weight,
            ref_pos_weight=ref_pos_weight,
            ref_theta1_weight=ref_theta1_weight,
            ref_theta2_weight=ref_theta2_weight,
        )
    elif env_name == "n_trailer2d":
        return NTrailer2d(
            num_trailers=num_trailers,
            case=case,
            env_config=env_config,
            dt=dt,
            H=H,
            motion_preference=motion_preference,
            collision_penalty=collision_penalty,
            hitch_penalty=hitch_penalty,
            enable_gated_rollout_collision=enable_gated_rollout_collision,
            enable_gated_rollout_hitch=enable_gated_rollout_hitch,
            enable_projection=enable_projection,
            enable_guidance=enable_guidance,
            reward_threshold=reward_threshold,
            ref_reward_threshold=ref_reward_threshold,
            max_w_theta=max_w_theta,
            hitch_angle_weight=hitch_angle_weight,
            l1=l1,
            l2=l2,
            lh=lh,
            lf1=lf1,
            lr=lr,
            lf2=lf2,
            lr2=lr2,
            tractor_width=tractor_width,
            trailer_width=trailer_width,
            v_max=v_max,
            delta_max_deg=delta_max_deg,
            d_thr_factor=d_thr_factor,
            k_switch=k_switch,
            steering_weight=steering_weight,
            preference_penalty_weight=preference_penalty_weight,
            heading_reward_weight=heading_reward_weight,
            terminal_reward_threshold=terminal_reward_threshold,
            terminal_reward_weight=terminal_reward_weight,
            ref_pos_weight=ref_pos_weight,
            ref_theta1_weight=ref_theta1_weight,
            ref_theta2_weight=ref_theta2_weight,
        )
    elif env_name == "acc_tt2d":
        return AccTractorTrailer2d(
            case=case,
            env_config=env_config,
            dt=dt,
            H=H,
            motion_preference=motion_preference,
            collision_penalty=collision_penalty,
            hitch_penalty=hitch_penalty,
            enable_gated_rollout_collision=enable_gated_rollout_collision,
            enable_gated_rollout_hitch=enable_gated_rollout_hitch,
            enable_projection=enable_projection,
            enable_guidance=enable_guidance,
            reward_threshold=reward_threshold,
            ref_reward_threshold=ref_reward_threshold,
            max_w_theta=max_w_theta,
            hitch_angle_weight=hitch_angle_weight,
            l1=l1,
            l2=l2,
            lh=lh,
            lf1=lf1,
            lr=lr,
            lf2=lf2,
            lr2=lr2,
            tractor_width=tractor_width,
            trailer_width=trailer_width,
            v_max=v_max,
            delta_max_deg=delta_max_deg,
            d_thr_factor=d_thr_factor,
            k_switch=k_switch,
            steering_weight=steering_weight,
            preference_penalty_weight=preference_penalty_weight,
            heading_reward_weight=heading_reward_weight,
            terminal_reward_threshold=terminal_reward_threshold,
            terminal_reward_weight=terminal_reward_weight,
            ref_pos_weight=ref_pos_weight,
            ref_theta1_weight=ref_theta1_weight,
            ref_theta2_weight=ref_theta2_weight,
            a_max=a_max,
            omega_max=omega_max,
        )
    elif env_name == "kinematic_bicycle2d":
        return KinematicBicycle2d(
            case=case,
            env_config=env_config,
            dt=dt,
            H=H,
            motion_preference=motion_preference,
            collision_penalty=collision_penalty,
            hitch_penalty=hitch_penalty,  # Will be ignored by bicycle model
            enable_gated_rollout_collision=enable_gated_rollout_collision,
            enable_gated_rollout_hitch=enable_gated_rollout_hitch,  # Will be ignored by bicycle model
            enable_projection=enable_projection,
            enable_guidance=enable_guidance,
            reward_threshold=reward_threshold,
            ref_reward_threshold=ref_reward_threshold,
            max_w_theta=max_w_theta,
            hitch_angle_weight=hitch_angle_weight,  # Will be ignored by bicycle model
            l1=l1,
            l2=l2,  # Will be ignored by bicycle model
            lh=lh,  # Will be ignored by bicycle model
            lf1=lf1,
            lr=lr,
            lf2=lf2,  # Will be ignored by bicycle model
            lr2=lr2,  # Will be ignored by bicycle model
            tractor_width=tractor_width,
            trailer_width=trailer_width,  # Will be ignored by bicycle model
            v_max=v_max,
            delta_max_deg=delta_max_deg,
            d_thr_factor=d_thr_factor,
            k_switch=k_switch,
            steering_weight=steering_weight,
            preference_penalty_weight=preference_penalty_weight,
            heading_reward_weight=heading_reward_weight,
            terminal_reward_threshold=terminal_reward_threshold,
            terminal_reward_weight=terminal_reward_weight,
            ref_pos_weight=ref_pos_weight,
            ref_theta1_weight=ref_theta1_weight,
            ref_theta2_weight=ref_theta2_weight,  # Will be ignored by bicycle model
        )
    else:
        raise ValueError(f"Unknown environment: {env_name}")
